memory: 500M
disk_quota: 500M
disable_internal_https: 'true'
run_migration: 'true'
aws_access_key: x
aws_secret_key: x
token_api_hmac_secret: something
rate_limiter_value: 200
rate_limiter_value_post: 100
rate_limiter_reqs_node: 200
rate_limiter_req_node_post: 100
rate_limiter_elevated_value_get: 100
rate_limiter_elevated_value_post: 200
rate_limiter_elevated_accounts: 31
redis_url: none


