server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT}

logging:
  level: INFO

connectorUrl: ${CONNECTOR_URL}
publicAuthUrl: ${PUBLIC_AUTH_URL}

jerseyClientConfig:
  disabledSecureConnection: ${DISABLE_INTERNAL_HTTPS}
  keystoreDir: "/etc/ssl/"
  keyStoreFile: "ca.cert.crt" # TODO need to replace with the exact file name
  keyStorePassword: ${KEY_STORE_PASSWORD}