server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT}

logging:
    level: INFO
    appenders:
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout
        logFormat: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

baseUrl: ${PUBLICAPI_BASE}
connectorUrl: ${CONNECTOR_URL}
publicAuthUrl: ${PUBLIC_AUTH_URL}

jerseyClientConfig:
  disabledSecureConnection: ${DISABLE_INTERNAL_HTTPS}

rateLimiter:
  rate: ${RATE_LIMITER_VALUE:-25}
  perMillis: ${RATE_LIMITER_PER_MILLIS:-1000}

apiKeyHmacSecret: ${TOKEN_API_HMAC_SECRET}
