server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}
  requestLog:
    appenders:
      - type: console
        target: stdout
        logFormat: "%h:%localPort %i{X-Request-Id} %i{X-Forwarded-For} %a [%t] \"%r\" %s %b %D %i{X-Forwarded-Proto} \"%i{Referer}\" \"%i{User-Agent}\""

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [thread=%thread] [level=%-5level] [logger=%logger{15}] [requestID=%X{X-Request-Id:-(none)}] [gateway_account_id=%X{gateway_account_id:-(none)}] - %msg%n"

baseUrl: ${PUBLICAPI_BASE}
connectorUrl: ${CONNECTOR_URL}
connectorDDUrl: ${CONNECTOR_DD_URL}
publicAuthUrl: ${PUBLIC_AUTH_URL}
ledgerUrl: ${LEDGER_URL}

graphiteHost: ${METRICS_HOST:-localhost}
graphitePort: ${METRICS_PORT:-8092}

jerseyClientConfig:
  disabledSecureConnection: ${DISABLE_INTERNAL_HTTPS:-false}

rateLimiter:  # rate = noOfReq per perMillis
  noOfReq: ${RATE_LIMITER_VALUE:-75}  # for requests except POST and across all publicapi instances.
  noOfReqForPost: ${RATE_LIMITER_VALUE_POST:-15} # for POST requests across all publicapi instances.
  noOfReqPerNode: ${RATE_LIMITER_VALUE_PER_NODE:-25}  # per public api instance, if Redis is unavailable
  noOfReqForPostPerNode: ${RATE_LIMITER_VALUE_PER_NODE_POST:-5}  # per public api instance, if Redis is unavailable
  perMillis: ${RATE_LIMITER_PER_MILLIS:-1000}

redis:
  # The redis server's address; required.
  endpoint: ${REDIS_URL:-localhost:6379}
  # Enables SSL connection. (default: false)  ???
  ssl: false
  # The configured timeout (in milliseconds) for redis connections in the connection pool.  (default: 2000)
  timeout: 2000

allowHttpForReturnUrl: ${ALLOW_HTTP_FOR_RETURN_URL:-false}

apiKeyHmacSecret: ${TOKEN_API_HMAC_SECRET}

# Caching authenticator.
authenticationCachePolicy: expireAfterWrite=1m
